// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PastryFlow.Infrastructure.Data;

#nullable disable

namespace PastryFlow.Infrastructure.Migrations
{
    [DbContext(typeof(PastryFlowDbContext))]
    partial class PastryFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PastryFlow.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BranchType")
                        .HasColumnType("integer");

                    b.Property<int>("City")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            BranchType = 1,
                            City = 1,
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 17, DateTimeKind.Utc).AddTicks(614),
                            IsActive = true,
                            Name = "Kırklareli Mutfak"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            BranchType = 1,
                            City = 2,
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 17, DateTimeKind.Utc).AddTicks(3021),
                            IsActive = true,
                            Name = "Edirne Mutfak"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            BranchType = 1,
                            City = 3,
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 17, DateTimeKind.Utc).AddTicks(3025),
                            IsActive = true,
                            Name = "Lüleburgaz Mutfak"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            BranchType = 2,
                            City = 1,
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 17, DateTimeKind.Utc).AddTicks(3027),
                            IsActive = true,
                            Name = "Kırklareli Tezgah"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            BranchType = 2,
                            City = 2,
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 17, DateTimeKind.Utc).AddTicks(3029),
                            IsActive = true,
                            Name = "Edirne Tezgah"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            BranchType = 2,
                            City = 3,
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 17, DateTimeKind.Utc).AddTicks(3031),
                            IsActive = true,
                            Name = "Lüleburgaz Tezgah"
                        });
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(3917),
                            IsActive = true,
                            Name = "KEK",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(9664),
                            IsActive = true,
                            Name = "EKMEK",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(9682),
                            IsActive = true,
                            Name = "MAYALILAR",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(9685),
                            IsActive = true,
                            Name = "KURABİYE",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(9722),
                            IsActive = true,
                            Name = "PASTALAR",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(9725),
                            IsActive = true,
                            Name = "İÇECEK",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(9728),
                            IsActive = true,
                            Name = "FIRIN",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 20, DateTimeKind.Utc).AddTicks(9730),
                            IsActive = true,
                            Name = "HAMMADDE",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.DailyStockSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CarryOverQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("DayWasteQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EndOfDayCount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EndOfDayWaste")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("IncomingTransferQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("OpeningStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OutgoingTransferQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReceivedFromDemands")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BranchId", "ProductId", "Date")
                        .IsUnique();

                    b.ToTable("DailyStockSummaries");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Demand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DemandNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("DriverUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductionBranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReceivedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalesBranchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductionBranchId");

                    b.HasIndex("SalesBranchId");

                    b.ToTable("Demands");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.DemandItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("RequestedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("ProductId");

                    b.ToTable("DemandItems");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductionBranchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductionBranchId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000001"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(3729),
                            IsActive = true,
                            Name = "KEK DİLİM",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000002"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(6989),
                            IsActive = true,
                            Name = "KEK KALIP BÜYÜK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000003"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7002),
                            IsActive = true,
                            Name = "KEK KALIP KÜÇÜK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000004"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7007),
                            IsActive = true,
                            Name = "KEK KALIP ORTA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000005"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7012),
                            IsActive = true,
                            Name = "KEK MUFİN",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000006"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7024),
                            IsActive = true,
                            Name = "EKŞİ MAYA (3'LÜ)",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000007"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7119),
                            IsActive = true,
                            Name = "EKŞİ MAYA (2'Lİ)",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000008"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7137),
                            IsActive = true,
                            Name = "ÇAVDAR",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000009"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7142),
                            IsActive = true,
                            Name = "TAHILLI",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000010"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7151),
                            IsActive = true,
                            Name = "MISIR",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000011"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7155),
                            IsActive = true,
                            Name = "TEKLİ BEYAZ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000012"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7159),
                            IsActive = true,
                            Name = "ÇİFTLİ BEYAZ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000013"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7164),
                            IsActive = true,
                            Name = "KEPEK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000014"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7168),
                            IsActive = true,
                            Name = "TAMBUĞDAY",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000015"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7172),
                            IsActive = true,
                            Name = "PİDE",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000016"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7176),
                            IsActive = true,
                            Name = "SANDVİÇ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000017"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7180),
                            IsActive = true,
                            Name = "SİYEZ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000018"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7191),
                            IsActive = true,
                            Name = "BÖREK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000019"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7195),
                            IsActive = true,
                            Name = "KAFKAS BÖREĞİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000020"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7206),
                            IsActive = true,
                            Name = "AÇMA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000021"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7210),
                            IsActive = true,
                            Name = "İÇLİ SİMİT",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000022"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7215),
                            IsActive = true,
                            Name = "PİZZA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000023"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7219),
                            IsActive = true,
                            Name = "POĞAÇA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000024"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7223),
                            IsActive = true,
                            Name = "POĞAÇA İRAN",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000025"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7228),
                            IsActive = true,
                            Name = "POĞAÇA SAKALLI",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000026"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7234),
                            IsActive = true,
                            Name = "SİMİT",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000027"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7243),
                            IsActive = true,
                            Name = "SU BÖREĞİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000028"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7247),
                            IsActive = true,
                            Name = "İÇLİ SANDVİÇ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000029"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7259),
                            IsActive = true,
                            Name = "ACIBADEM",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000030"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7264),
                            IsActive = true,
                            Name = "BEZE BÜYÜK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000031"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7269),
                            IsActive = true,
                            Name = "BEZE KUTU",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000032"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7307),
                            IsActive = true,
                            Name = "GÜLEN YÜZ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000033"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7312),
                            IsActive = true,
                            Name = "KURABİYE EKSTRA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000034"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7321),
                            IsActive = true,
                            Name = "KURABİYE MUZ / BONCUK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000035"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7381),
                            IsActive = true,
                            Name = "KURABİYE SADE",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000036"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7387),
                            IsActive = true,
                            Name = "KURABİYE ŞAM",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000037"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7392),
                            IsActive = true,
                            Name = "KURABİYE TAHİNLİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000038"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7397),
                            IsActive = true,
                            Name = "KURABİYE UN",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000039"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7401),
                            IsActive = true,
                            Name = "KURU PASTA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000040"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7406),
                            IsActive = true,
                            Name = "KURABİYE TART",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000041"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7411),
                            IsActive = true,
                            Name = "KANDİL SİMİDİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000042"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7419),
                            IsActive = true,
                            Name = "ALMAN PASTASI",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000043"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7424),
                            IsActive = true,
                            Name = "RULO SARMA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000044"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7428),
                            IsActive = true,
                            Name = "PASTA ADET",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000045"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7432),
                            IsActive = true,
                            Name = "PASTA CHEESECAKE",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000046"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7436),
                            IsActive = true,
                            Name = "PASTA B1",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000047"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7441),
                            IsActive = true,
                            Name = "PASTA NO 0",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000048"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7445),
                            IsActive = true,
                            Name = "PASTA NO 1",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000049"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7449),
                            IsActive = true,
                            Name = "FİGÜR-BUDAPEŞTE-SEBASTİAN",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000050"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7455),
                            IsActive = true,
                            Name = "SÜTLÜ TATLILAR",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000051"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7460),
                            IsActive = true,
                            Name = "TRİLEÇE",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000052"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7464),
                            IsActive = true,
                            Name = "SİPARİŞ PASTA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000053"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7469),
                            IsActive = true,
                            Name = "PASTA KG",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000054"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7475),
                            IsActive = true,
                            Name = "AYRAN",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000055"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7480),
                            IsActive = true,
                            Name = "ÇAY SATIŞ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000056"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7484),
                            IsActive = true,
                            Name = "ESPRESSO",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000057"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7489),
                            IsActive = true,
                            Name = "GAZLI İÇECEK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000058"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7495),
                            IsActive = true,
                            Name = "LİMONATA",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000059"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7499),
                            IsActive = true,
                            Name = "MEYVE SUYU",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000060"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7503),
                            IsActive = true,
                            Name = "SODA MEYVELİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000061"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7508),
                            IsActive = true,
                            Name = "SODA SADE",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000062"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7512),
                            IsActive = true,
                            Name = "SU 0.5 L",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000063"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7516),
                            IsActive = true,
                            Name = "TÜRK KAHVESİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000064"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7520),
                            IsActive = true,
                            Name = "BİTKİ ÇAYI",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000065"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7525),
                            IsActive = true,
                            Name = "PİKNİK ÜRÜNLER",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000066"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7580),
                            IsActive = true,
                            Name = "KAHVALTI TABAĞI",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000067"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7586),
                            IsActive = true,
                            Name = "GALETE",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000068"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7591),
                            IsActive = true,
                            Name = "EKMEK BEYAZ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000069"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7596),
                            IsActive = true,
                            Name = "EKMEK ÇEŞİT",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000070"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7600),
                            IsActive = true,
                            Name = "EKMEK KEPEK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000071"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7605),
                            IsActive = true,
                            Name = "EKMEK MISIR",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000072"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7609),
                            IsActive = true,
                            Name = "EKMEK SANDVİÇ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000073"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7613),
                            IsActive = true,
                            Name = "TAHILLI EKMEK",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000074"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7619),
                            IsActive = true,
                            Name = "PİDE ÇİFTLİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000075"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7623),
                            IsActive = true,
                            Name = "TANDIR EKMEĞİ",
                            ProductType = 2,
                            ProductionBranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000076"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7629),
                            IsActive = true,
                            Name = "UN",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000077"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7634),
                            IsActive = true,
                            Name = "TUZ",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000078"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7638),
                            IsActive = true,
                            Name = "ŞEKER",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000079"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7642),
                            IsActive = true,
                            Name = "MAYA",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000080"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7646),
                            IsActive = true,
                            Name = "TEREYAĞI",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000081"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7650),
                            IsActive = true,
                            Name = "MARGARİN",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000082"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7656),
                            IsActive = true,
                            Name = "KAKAO",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000083"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7661),
                            IsActive = true,
                            Name = "KABARTMA TOZU",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000084"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7665),
                            IsActive = true,
                            Name = "NİŞASTA",
                            ProductType = 1,
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000085"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7670),
                            IsActive = true,
                            Name = "SÜT",
                            ProductType = 1,
                            Unit = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000086"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7674),
                            IsActive = true,
                            Name = "KREMA",
                            ProductType = 1,
                            Unit = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000087"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7678),
                            IsActive = true,
                            Name = "AYÇİÇEK YAĞI",
                            ProductType = 1,
                            Unit = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-000000000088"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 21, DateTimeKind.Utc).AddTicks(7683),
                            IsActive = true,
                            Name = "YUMURTA",
                            ProductType = 1,
                            Unit = 1
                        });
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DriverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromBranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReceivedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToBranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromBranchId");

                    b.HasIndex("ToBranchId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.TransferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ReceivedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferItems");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(4120),
                            Email = "admin@pastryflow.com",
                            FullName = "Admin Kullanıcı",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(7171),
                            Email = "kirklareli.mutfak@pastryflow.com",
                            FullName = "Kırklareli Üretim",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(7810),
                            Email = "edirne.mutfak@pastryflow.com",
                            FullName = "Edirne Üretim",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(7822),
                            Email = "luleburgaz.mutfak@pastryflow.com",
                            FullName = "Lüleburgaz Üretim",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(7825),
                            Email = "kirklareli.tezgah@pastryflow.com",
                            FullName = "Kırklareli Satış",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(7828),
                            Email = "edirne.tezgah@pastryflow.com",
                            FullName = "Edirne Satış",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333307"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(7831),
                            Email = "luleburgaz.tezgah@pastryflow.com",
                            FullName = "Lüleburgaz Satış",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333308"),
                            CreatedAt = new DateTime(2026, 4, 16, 8, 44, 2, 18, DateTimeKind.Utc).AddTicks(7834),
                            Email = "sofor@pastryflow.com",
                            FullName = "Şoför",
                            IsActive = true,
                            PasswordHash = "$2a$11$NleqkNOCjv3N1YWwrJYYfuHYXvpO5vaE1.It3fUTKLgHrTkXCABWO",
                            Role = 4
                        });
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Waste", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WasteType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Wastes");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.DailyStockSummary", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Demand", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Branch", "ProductionBranch")
                        .WithMany()
                        .HasForeignKey("ProductionBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Branch", "SalesBranch")
                        .WithMany()
                        .HasForeignKey("SalesBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ProductionBranch");

                    b.Navigation("SalesBranch");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.DemandItem", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.Demand", "Demand")
                        .WithMany("Items")
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Demand");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Product", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Branch", "ProductionBranch")
                        .WithMany("Products")
                        .HasForeignKey("ProductionBranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ProductionBranch");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.Branch", "FromBranch")
                        .WithMany()
                        .HasForeignKey("FromBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Branch", "ToBranch")
                        .WithMany()
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromBranch");

                    b.Navigation("ToBranch");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.TransferItem", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Transfer", "Transfer")
                        .WithMany("Items")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.User", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Waste", b =>
                {
                    b.HasOne("PastryFlow.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PastryFlow.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Demand", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PastryFlow.Domain.Entities.Transfer", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
